name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.12.0
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.0

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m pytest tests

    - name: Run coverage
      run: |
        pip install pytest-cov
        pytest --cov=./ --cov-fail-under=90
        coverage report -m